# Generated by Django 3.0.5 on 2020-05-03 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200503_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('slack_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('email', models.TextField(null=True)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='message_text',
            field=models.TextField(default='Hi'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Poll')),
                ('slack_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.SlackUser')),
            ],
        ),
    ]
