# Generated by Django 3.0.5 on 2020-05-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200503_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollusermeta',
            old_name='response_url',
            new_name='channel',
        ),
    ]
