# Generated by Django 3.0.5 on 2020-05-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_pollschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollschedule',
            old_name='name_poll',
            new_name='poll',
        ),
    ]
