# Generated by Django 3.0.5 on 2020-05-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200516_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll')),
            ],
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='poll_answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.PollAnswer'),
            preserve_default=False,
        ),
    ]
