# Generated by Django 3.0.5 on 2020-05-16 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200516_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='slack_user',
        ),
        migrations.AddField(
            model_name='pollanswer',
            name='slack_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.SlackUser'),
            preserve_default=False,
        ),
    ]
